# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 11:51
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('image', models.TextField(verbose_name='Image')),
                ('publishing_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.Category', verbose_name='Category')),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Time information')),
                ('value_count', models.IntegerField(default=1)),
                ('value_type', models.CharField(default='YEAR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInfoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeValue1', models.CharField(blank=True, max_length=120, verbose_name='')),
                ('timeValue2', models.CharField(blank=True, max_length=120, verbose_name='')),
                ('timeInfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.TimeInfo', verbose_name='TimeInfoValue')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='timeInfoGroup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.TimeInfoGroup', verbose_name='TimeInfoGroup'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Writer'),
        ),
    ]
