# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171021_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Time information')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='timeValue1',
            field=models.CharField(blank=True, max_length=120, verbose_name=''),
        ),
        migrations.AddField(
            model_name='post',
            name='timeValue2',
            field=models.CharField(blank=True, max_length=120, verbose_name=''),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.Category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='timeInfo',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.TimeInfo', verbose_name='TimeInfoValue'),
            preserve_default=False,
        ),
    ]
