# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171021_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Time information')),
                ('value_count', models.IntegerField(default=1)),
                ('value_type', models.CharField(default='YEAR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInfoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeValue1', models.CharField(blank=True, max_length=120, verbose_name='')),
                ('timeValue2', models.CharField(blank=True, max_length=120, verbose_name='')),
                ('timeInfo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.TimeInfo', verbose_name='TimeInfoValue')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.Category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='timeInfoGroup',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='post.TimeInfoGroup', verbose_name='TimeInfoGroup'),
            preserve_default=False,
        ),
    ]
